### ISSUE TITLE
Crash and attempt at deleting Cache

### ISSUE THREAD

**Issue by MarkMcP89** [L3tum/KCDModMerger#1]
Popup when using program.
"Program encountered a critical exception! Clear Cache? "
[KCDModMerger.log](https://github.com/L3tum/KCDModMerger/files/1868700/KCDModMerger.log)

**Comment by L3tum** [comment]
TIL some watchers are not universally available, hotfix coming

**Comment by MarkMcP89** [comment]
I am HolyDeath3000 on Nexus. Which is quicker to let you know about bugs here? or Nexus?

**Comment by L3tum** [comment]
Please check the newest version, should be fixed

**Comment by L3tum** [comment]
I'm getting emails on here, but not on nexus, so definitely here. Though I do work full time so I might not respond that much on both during the week

**Comment by MarkMcP89** [comment]
Totally fine. I work usually right now 5 days a week. And saw that it might be good to try mod mergers. Also I just bought this game like 3 to 4 days ago. Love modding games. So in any way I can help I will definitely help out. Testing stuff. :)

**Comment by L3tum** [comment]
Wow, thank you! It'd be really good to have some "beta" testers for new stuff, since up til now I've just been running a few "known complicated" mods on my system, but that's not really telling^^

I've bought this game back when it was in beta because a friend pushed me onto it. I can definitely recommend the soundtrack, it's definitely one of the better ones. Apparently some tweets by the devs are also worth checking out. I've been thinking about doing some modding again and this was the perfect opportunity. If you want to do some coding yourself you can basically just clone this repository. There hasn't been anything done besides a standard C# WPF project.

Just a question though, what sort of hard drives do you have? HDD or SSD? Multiple? Cause the one that crashed was for disk usage, which is just strange.

**Comment by MarkMcP89** [comment]
I have a 3TB WD Blue HDD actually. Only one. And 2 partitions. I don't code stuff but I do a lot of stress testing of certain mods. If familiar with Kaldaien SpecialK mod on Steam group I am very active there as well. Was helping him with his mod since Batman AK days. So if you need an actual tester I am here to help. 

I don't know any coding but I do find and test things to see if anything is work. Just out of curiosity if there is no conflicts detected it won't allow a merge?

Edit: Tested it with a mod that I know has conflict and detected it. So merge button stays greyed out until actual conflict is noticed. Good idea too.

**Comment by L3tum** [comment]
Ah, I doubt WD drives don't support measuring drive usage. Partitions *shouldn't* be a problem, I have a few as well. Well, maybe I'll find it at some point....

That's pretty good! I want the next release to be a bit more organized, with its own branch, beta release and better testing. I need to write a few automatic tests anyways, but anything that involves the actual system (performance watchers, files etc) needs to be tested on multiple machines, so you'd really help me out there!

Yeah, I had the suspicion that a few reports of "no merged files" were because there were no conflicts to merge, so I greyed it out unless there are any now. I need to add a "merge all" button though, I think, to allow the copy all option to work without conflicts.
